### ISSUE TITLE
Indentation (Tab and Space)

### ISSUE THREAD

**Issue by karbowiak** [gossi/php-code-generator#9]
Hi there!
Just started using it, and it's awesome for what i'm doing.

However, the indentation is done with tabs, any chance of adding a config that will allow me (and others) to switch it to spaces? :)

**Comment by marcj** [comment]
+1

**Comment by gossi** [comment]
Nope, spaces suck!

Yet, I've created the [gossi/php-code-formatter](https://github.com/gossi/php-code-formatter) project to address this.

**Comment by marcj** [comment]
Oh, well, then it looks like it's time for a fork which addresses the need of the wider PHP community that use spaces. :/

**Comment by gossi** [comment]
Nope. That's the wrong way.

There are no real code formatter packages available, that's why I created one. Although it has very limited functionality at the moment. Yet what it does, it supports code style profiles. The right way would be to strengthen the code formatter library and make it a depdency on the code-generator project. For code generation pass the profile used for formatting to the generator and that's the way to go.

**Comment by gossi** [comment]
Refer to #23 to discuss ideas there.
